-- Create a table for storing study notes
create table notes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  subject text not null,
  grade text not null,
  type text default 'Note',
  author text default 'Anonymous',
  file_url text not null,
  file_size text,
  downloads integer default 0
);

-- Create a table for community requests
create table requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_name text not null,
  grade text not null,
  subject text not null,
  note_content text not null,
  upvotes integer default 0,
  fulfilled boolean default false
);

-- Set up Row Level Security (RLS)
-- For this crisis app, we allow public read/write access to facilitate easy sharing.
-- In a long-term production app, you would add authentication.

alter table notes enable row level security;
alter table requests enable row level security;

-- Policy for Notes: Everyone can read
create policy "Public Notes Access"
  on notes for select
  using ( true );

-- Policy for Notes: Everyone can insert (upload)
create policy "Public Notes Upload"
  on notes for insert
  with check ( true );

-- Policy for Requests: Everyone can read
create policy "Public Requests Access"
  on requests for select
  using ( true );

-- Policy for Requests: Everyone can insert (post request)
create policy "Public Requests Insert"
  on requests for insert
  with check ( true );

-- Policy for Requests: Everyone can update (upvote/fulfill)
create policy "Public Requests Update"
  on requests for update
  using ( true );

-- Storage Bucket Setup (You need to create a bucket named 'study-materials' in the dashboard)
-- This SQL just sets the policy if the bucket exists.
-- insert into storage.buckets (id, name) values ('study-materials', 'study-materials');

-- Storage Policy: Public Read
-- create policy "Public Access"
--   on storage.objects for select
--   using ( bucket_id = 'study-materials' );

-- Storage Policy: Public Upload
-- create policy "Public Upload"
--   on storage.objects for insert
--   with check ( bucket_id = 'study-materials' );
